### ISSUE TITLE
Not registered as formatter

### ISSUE THREAD

**Issue by sasha-3ap** [Dev-Snippets/vscode-google-java-format-provider#1]
If I disable java formatter from redhat plugins and install this formatter, when I try to format java code I get message that formatter is not installed.

**Comment by jhstudiotest** [comment]
It is very nice extension and working well with node version 11.4.0.
I attach my configuration as below, so I think it is working well if you guy add it to settings.json file.

    "google-java-format.language.java.enable": true,
    // "editor.formatOnSave": true,
    "editor.defaultFormatter": "wx-chevalier.google-java-format",
    "[java]": {
        "editor.defaultFormatter": "wx-chevalier.google-java-format"
    },

**Comment by haysmike** [comment]
Ran into the same issue, it looks like there's some issue with its dependencies:

```
[2020-05-21 10:49:41.094] [exthost] [error] Activating extension wx-chevalier.google-java-format failed due to an error:
[2020-05-21 10:49:41.096] [exthost] [error] Error: Cannot find module 'sax'
Require stack:
- /Users/mikehays/.vscode/extensions/wx-chevalier.google-java-format-0.0.1/out/src/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
	at Module._load (internal/modules/cjs/loader.js:622:27)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:955:769)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:106)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:524)
	at Object.<anonymous> (/Users/mikehays/.vscode/extensions/wx-chevalier.google-java-format-0.0.1/out/src/extension.js:6:13)
	at Module.o._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:749)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
	at Module.load (internal/modules/cjs/loader.js:735:32)
	at Module._load (internal/modules/cjs/loader.js:648:12)
	at Module._load (electron/js2c/asar.js:717:26)
	at Function.Module._load (electron/js2c/asar.js:717:26)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:955:769)
	at Function.n._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:925:106)
	at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:921:391)
	at Module.require (internal/modules/cjs/loader.js:775:19)
	at require (internal/modules/cjs/helpers.js:68:18)
	at Function.s [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:33:115)
	at h._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:926:266)
	at h._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:822:856)
	at h._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:821:937)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:883)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:859)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:537
	at Array.map (<anonymous>)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:525)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:598:594)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:596:14)
	at h._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:618)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:829:401
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

Looking in `~/.vscode/extensions/wx-chevalier.google-java-format-0.0.1`, I can see that there is no `node_modules` folder.

**Comment by xbeta** [comment]
@haysmike So I guess you don't use this `vscode-google-java-format-provider` plugin anymore right?

**Comment by raethlein** [comment]
I just figured out that the source code of the extension when installed via VS Code is not the same as the one in the Master branch. After going into the extensions folder and installing the node_modules via `npm install`, the extension is loaded but will throw another error upon executing "Format Document" (something with a wrong flag passed ot the `google-java-format` command).

You can use the plugin with the following workaround:
1.  download the code of the master branch
1. execute `npm install` in the folder
1. remove the `__metadata` field in the `package.json` and set a different name (so that VS Code does not think the actual plugin is installed; it will then show the extension with the new name in the extenion's view)
1. copy the whole folder into the `~/.vscode/extensions` folder. 

After restarting VS Code, the command `Format Document` should work.
